// Auto-generated by build.js - do not edit manually
const artwork = [
  {
    "title": "Youre Welcome 34816",
    "artist": "kody",
    "file": "artwork/kody/youre-welcome-34816.mp4",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Untitled Video   Made With Clipchamp 95",
    "artist": "kody",
    "file": "artwork/kody/Untitled_video_-_Made_with_Clipchamp_95.mov",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Untitled Video   Made With Clipchamp (49)",
    "artist": "kody",
    "file": "artwork/kody/Untitled video - Made with Clipchamp (49).gif",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Untitled Video   Made With Clipchamp (41)",
    "artist": "kody",
    "file": "artwork/kody/Untitled video - Made with Clipchamp (41).gif",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Untitled Video   Made With Clipchamp (37)",
    "artist": "kody",
    "file": "artwork/kody/Untitled video - Made with Clipchamp (37).gif",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "RwerwerewRERWEWR",
    "artist": "kody",
    "file": "artwork/kody/rwerwerewRERWEWR.jpg",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Man",
    "artist": "kody",
    "file": "artwork/kody/man.jpg",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Juno",
    "artist": "kody",
    "file": "artwork/kody/juno.png",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Hxh",
    "artist": "kody",
    "file": "artwork/kody/hxh.jpg",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Fsdfsdasddgfgfasd",
    "artist": "kody",
    "file": "artwork/kody/fsdfsdasddgfgfasd.png",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Flim",
    "artist": "kody",
    "file": "artwork/kody/flim.png",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "FISH",
    "artist": "kody",
    "file": "artwork/kody/FISH.mp4",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Base Character Color",
    "artist": "kody",
    "file": "artwork/kody/base_character_color.png",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Ascii Art  15  Removebg Preview",
    "artist": "kody",
    "file": "artwork/kody/ascii-art__15_-removebg-preview.png",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Ascii Art (16)",
    "artist": "kody",
    "file": "artwork/kody/ascii-art (16).png",
    "medium": "",
    "year": "2026"
  },
  {
    "title": "Archie",
    "artist": "kody",
    "file": "artwork/kody/archie.mov",
    "medium": "",
    "year": "2026"
  }
];