// Auto-generated by build.js - do not edit manually
const artwork = [
  {
    "title": "Cat",
    "category": "analog",
    "file": "artwork/analog/cat.jpg",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "HxH",
    "category": "analog",
    "file": "artwork/analog/HxH.jpg",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "Juno",
    "category": "analog",
    "file": "artwork/analog/juno.png",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "Man",
    "category": "analog",
    "file": "artwork/analog/man.jpg",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "Wolf Pastel",
    "category": "analog",
    "file": "artwork/analog/Wolf Pastel.png",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "Archie",
    "category": "digital",
    "file": "artwork/digital/archie.mov",
    "medium": "Video",
    "year": "2026"
  },
  {
    "title": "Dust & Iron",
    "category": "digital",
    "file": "artwork/digital/Dust & Iron.png",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "FISH",
    "category": "digital",
    "file": "artwork/digital/FISH.mp4",
    "medium": "Video",
    "year": "2026"
  },
  {
    "title": "Horse",
    "category": "digital",
    "file": "artwork/digital/horse.gif",
    "medium": "GIF",
    "year": "2026"
  },
  {
    "title": "IronDraw",
    "category": "digital",
    "file": "artwork/digital/IronDraw.mp4",
    "medium": "Video",
    "year": "2026"
  },
  {
    "title": "Masks",
    "category": "digital",
    "file": "artwork/digital/Masks.jpg",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "Queen",
    "category": "digital",
    "file": "artwork/digital/queen.png",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "Sci Fi",
    "category": "digital",
    "file": "artwork/digital/sci-fi.mp4",
    "medium": "Video",
    "year": "2026"
  },
  {
    "title": "2D Prototype Game",
    "category": "game-dev",
    "file": "artwork/game-dev/2D Prototype Game.gif",
    "medium": "GIF",
    "year": "2026"
  },
  {
    "title": "3D Prototype Game",
    "category": "game-dev",
    "file": "artwork/game-dev/3D Prototype Game.gif",
    "medium": "GIF",
    "year": "2026"
  },
  {
    "title": "Call It Dock",
    "category": "game-dev",
    "file": "artwork/game-dev/Call It Dock.jpg",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "Call It Steam Header",
    "category": "game-dev",
    "file": "artwork/game-dev/Call It Steam Header.gif",
    "medium": "GIF",
    "year": "2026"
  },
  {
    "title": "Chum Studios Banner",
    "category": "game-dev",
    "file": "artwork/game-dev/Chum Studios Banner.gif",
    "medium": "GIF",
    "year": "2026"
  },
  {
    "title": "Dithered Prototype",
    "category": "game-dev",
    "file": "artwork/game-dev/Dithered Prototype.mp4",
    "medium": "Video",
    "year": "2026"
  },
  {
    "title": "Koma",
    "category": "game-dev",
    "file": "artwork/game-dev/Koma.png",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "Mr. Flim",
    "category": "game-dev",
    "file": "artwork/game-dev/Mr. Flim.png",
    "medium": "Image",
    "year": "2026"
  },
  {
    "title": "Street Prototype",
    "category": "game-dev",
    "file": "artwork/game-dev/Street Prototype.gif",
    "medium": "GIF",
    "year": "2026"
  },
  {
    "title": "Wireframe Hand",
    "category": "game-dev",
    "file": "artwork/game-dev/Wireframe Hand.png",
    "medium": "Image",
    "year": "2026"
  }
];