// Auto-generated by build.js - do not edit manually
const artwork = [
  {
    "title": "Sci Fi",
    "artist": "kody",
    "file": "artwork/kody/sci-fi.mp4",
    "medium": "Video",
    "year": "2026"
  },
  {
    "title": "Queen",
    "artist": "kody",
    "file": "artwork/kody/queen.png",
    "medium": "Digital",
    "year": "2026"
  },
  {
    "title": "Mr. Flim",
    "artist": "kody",
    "file": "artwork/kody/Mr. Flim.png",
    "medium": "Digital",
    "year": "2026"
  },
  {
    "title": "Man",
    "artist": "kody",
    "file": "artwork/kody/man.jpg",
    "medium": "Digital",
    "year": "2026"
  },
  {
    "title": "Koma",
    "artist": "kody",
    "file": "artwork/kody/Koma.png",
    "medium": "Digital",
    "year": "2026"
  },
  {
    "title": "Juno",
    "artist": "kody",
    "file": "artwork/kody/juno.png",
    "medium": "Digital",
    "year": "2026"
  },
  {
    "title": "IronDraw",
    "artist": "kody",
    "file": "artwork/kody/IronDraw.mp4",
    "medium": "Video",
    "year": "2026"
  },
  {
    "title": "HxH",
    "artist": "kody",
    "file": "artwork/kody/HxH.jpg",
    "medium": "Digital",
    "year": "2026"
  },
  {
    "title": "Horse",
    "artist": "kody",
    "file": "artwork/kody/horse.gif",
    "medium": "GIF",
    "year": "2026"
  },
  {
    "title": "FISH",
    "artist": "kody",
    "file": "artwork/kody/FISH.mp4",
    "medium": "Video",
    "year": "2026"
  },
  {
    "title": "Dust & Iron",
    "artist": "kody",
    "file": "artwork/kody/Dust & Iron.png",
    "medium": "Digital",
    "year": "2026"
  },
  {
    "title": "Cat",
    "artist": "kody",
    "file": "artwork/kody/cat.jpg",
    "medium": "Digital",
    "year": "2026"
  },
  {
    "title": "Archie",
    "artist": "kody",
    "file": "artwork/kody/archie.mov",
    "medium": "Video",
    "year": "2026"
  },
  {
    "title": "3D Prototype Game",
    "artist": "kody",
    "file": "artwork/kody/3D Prototype Game.gif",
    "medium": "GIF",
    "year": "2026"
  },
  {
    "title": "2D Prototype Game",
    "artist": "kody",
    "file": "artwork/kody/2D Prototype Game.gif",
    "medium": "GIF",
    "year": "2026"
  }
];