const fs = require('fs');
const path = require('path');

const artworkDir = path.join(__dirname, 'artwork');
const categories = ['analog', 'digital', 'game-dev'];
const validExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.mp4', '.mov', '.webm'];

const artwork = [];

categories.forEach(category => {
  const categoryDir = path.join(artworkDir, category);

  if (!fs.existsSync(categoryDir)) {
    fs.mkdirSync(categoryDir, { recursive: true });
    return;
  }

  const files = fs.readdirSync(categoryDir);

  files.forEach(file => {
    const ext = path.extname(file).toLowerCase();
    if (!validExtensions.includes(ext)) return;

    const name = path.basename(file, ext);
    // Convert filename to title: "my-cool-art" -> "My Cool Art"
    const title = name
      .replace(/[-_]/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase());

    let medium = 'Image';
    if (['.mp4', '.mov', '.webm'].includes(ext)) medium = 'Video';
    else if (ext === '.gif') medium = 'GIF';

    artwork.push({
      title,
      category,
      file: `artwork/${category}/${file}`,
      medium,
      year: new Date().getFullYear().toString()
    });
  });
});

// Group by category (in the order above), then by filename within each group
artwork.sort((a, b) =>
  categories.indexOf(a.category) - categories.indexOf(b.category) || a.file.localeCompare(b.file));

const output = `// Auto-generated by build.js - do not edit manually
const artwork = ${JSON.stringify(artwork, null, 2)};`;

fs.writeFileSync(path.join(__dirname, 'artwork.js'), output);
console.log(`Generated artwork.js with ${artwork.length} pieces`);
