const fs = require('fs');
const path = require('path');

const artworkDir = path.join(__dirname, 'artwork');
const artists = ['emma', 'kody'];
const validExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif', '.mp4', '.mov', '.webm'];

const artwork = [];

artists.forEach(artist => {
  const artistDir = path.join(artworkDir, artist);

  if (!fs.existsSync(artistDir)) {
    fs.mkdirSync(artistDir, { recursive: true });
    return;
  }

  const files = fs.readdirSync(artistDir);

  files.forEach(file => {
    const ext = path.extname(file).toLowerCase();
    if (!validExtensions.includes(ext)) return;

    const name = path.basename(file, ext);
    // Convert filename to title: "my-cool-art" -> "My Cool Art"
    const title = name
      .replace(/[-_]/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase());

    artwork.push({
      title,
      artist,
      file: `artwork/${artist}/${file}`,
      medium: '',
      year: new Date().getFullYear().toString()
    });
  });
});

// Sort by filename (newest first if using timestamps, or alphabetically)
artwork.sort((a, b) => b.file.localeCompare(a.file));

const output = `// Auto-generated by build.js - do not edit manually
const artwork = ${JSON.stringify(artwork, null, 2)};`;

fs.writeFileSync(path.join(__dirname, 'artwork.js'), output);
console.log(`Generated artwork.js with ${artwork.length} pieces`);
